In [9]:
import numpy as np

numpy array

In [10]:
benimListem = [20,30,40]

type(benimListem)

list

In [11]:
np.array(benimListem)

array([20, 30, 40])

In [12]:
matrixlistesi = [[10,20,30],[20,40,60],[30,60,90]]
type(matrixlistesi)

list

In [13]:
matrixlistesi[1][0]

20

In [14]:
np.array(matrixlistesi)

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

arange

In [15]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

zeros

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

linspace

In [29]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

eye

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

random

In [62]:
np.random.rand(8)

array([0.68035078, 0.20922449, 0.43876468, 0.47920628, 0.26316617,
       0.4669442 , 0.78077008, 0.94038308])

In [63]:
np.random.rand(4,4)

array([[0.13992452, 0.33091191, 0.34276066, 0.72866913],
       [0.07435298, 0.64563273, 0.58066242, 0.70168227],
       [0.98672391, 0.94841861, 0.29812687, 0.44531001],
       [0.8821907 , 0.53991098, 0.86094016, 0.22051184]])

In [76]:
np.random.randint(1,10)

8

In [89]:
np.random.randint(1,10,5)

array([7, 6, 4, 9, 1], dtype=int32)

In [91]:
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [92]:
benimRandomDizim = np.random.randint(0,100,30)
benimRandomDizim

array([97, 75, 33, 58, 21, 45, 56, 28, 76, 56, 93, 45, 11, 19,  0, 56, 63,
       23, 37, 55, 29, 17, 72, 10, 32, 59, 78, 74, 97, 66], dtype=int32)

numpy dizi metodları

In [97]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [100]:
benimNumpyDizim.max()

np.int64(29)

In [101]:
benimNumpyDizim.min()

np.int64(0)

In [102]:
benimNumpyDizim.argmax()

np.int64(29)

In [103]:
benimNumpyDizim.argmin()

np.int64(0)

In [104]:
benimNumpyDizim.shape

(30,)

In [107]:
reshapedizi = benimNumpyDizim.reshape(5,6)
reshapedizi.shape

(5, 6)