In [18]:
import numpy as np

In [6]:
bennimDizim = np.arange(1, 11)
bennimDizim[3:5] = -5
bennimDizim

array([ 1,  2,  3, -5, -5,  6,  7,  8,  9, 10])

In [10]:
baskaDizi = np.arange(0, 24)
slicegDizi=baskaDizi[4:9]
slicegDizi[:] = -10
baskaDizi   

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [12]:
ornekdizi = np.arange(1, 24)
ornekdizikopya = ornekdizi.copy()
ornekdizikopya[3:5] = -5
ornekdizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

matrix

In [13]:
benimListem = [[10,20,30], [40,50,60], [70,80,90]]
benimMatrisxListem = np.array(benimListem)
benimMatrisxListem

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
benimMatrisxListem[0][1]

np.int64(20)

In [14]:
benimMatrisxListem[0,1]

np.int64(20)

In [26]:
benimMatrisxListem[1:,1]

array([50, 80])

In [25]:
benimMatrisxListem[0:,1]

array([20, 50, 80])

In [27]:
benimMatrisxListem[1:,1:]

array([[50, 60],
       [80, 90]])

In [29]:
yeniListe = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25]]
yeniMatris = np.array(yeniListe)
yeniMatris

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
yeniMatris[[0,2,4]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

operasyonlar

In [20]:
yeniBirDizi = np.random.rand(1,100,20)
yeniBirDizi

array([[[0.79744835, 0.24328357, 0.70220577, ..., 0.57998471,
         0.06466782, 0.92734927],
        [0.96801489, 0.92987462, 0.34003231, ..., 0.23527811,
         0.6549753 , 0.44876629],
        [0.15782416, 0.45902237, 0.18326203, ..., 0.93817944,
         0.23259506, 0.67314806],
        ...,
        [0.7945064 , 0.96375597, 0.83812234, ..., 0.78175225,
         0.46256244, 0.68098804],
        [0.23802111, 0.17145234, 0.74614258, ..., 0.19114315,
         0.61744485, 0.62723256],
        [0.4082726 , 0.84955449, 0.00935678, ..., 0.78093153,
         0.17738177, 0.15447102]]], shape=(1, 100, 20))

In [21]:
yeniBirDizi > 0.5

array([[[ True, False,  True, ...,  True, False,  True],
        [ True,  True, False, ..., False,  True, False],
        [False, False, False, ...,  True, False,  True],
        ...,
        [ True,  True,  True, ...,  True, False,  True],
        [False, False,  True, ..., False,  True,  True],
        [False,  True, False, ...,  True, False, False]]],
      shape=(1, 100, 20))

In [22]:
sonuc = (yeniBirDizi > 0.5)
sonuc

array([[[ True, False,  True, ...,  True, False,  True],
        [ True,  True, False, ..., False,  True, False],
        [False, False, False, ...,  True, False,  True],
        ...,
        [ True,  True,  True, ...,  True, False,  True],
        [False, False,  True, ..., False,  True,  True],
        [False,  True, False, ...,  True, False, False]]],
      shape=(1, 100, 20))

In [23]:
yeniBirDizi[sonuc]

array([0.79744835, 0.70220577, 0.74869462, ..., 0.62735528, 0.89530156,
       0.78093153], shape=(1036,))

In [24]:
yeniBirDizi[yeniBirDizi > 0.5]

array([0.79744835, 0.70220577, 0.74869462, ..., 0.62735528, 0.89530156,
       0.78093153], shape=(1036,))

In [25]:
sonDizi = np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [28]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [29]:
sonDizi / sonDizi

C:\Users\tasta\AppData\Local\Temp\ipykernel_5908\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [30]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [31]:
np.max(sonDizi)

np.int64(23)