In [1]:
import numpy as np

In [6]:
bennimDizim = np.arange(1, 11)
bennimDizim[3:5] = -5
bennimDizim

array([ 1,  2,  3, -5, -5,  6,  7,  8,  9, 10])

In [10]:
baskaDizi = np.arange(0, 24)
slicegDizi=baskaDizi[4:9]
slicegDizi[:] = -10
baskaDizi   

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [12]:
ornekdizi = np.arange(1, 24)
ornekdizikopya = ornekdizi.copy()
ornekdizikopya[3:5] = -5
ornekdizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

matrix

In [13]:
benimListem = [[10,20,30], [40,50,60], [70,80,90]]
benimMatrisxListem = np.array(benimListem)
benimMatrisxListem

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
benimMatrisxListem[0][1]

np.int64(20)

In [14]:
benimMatrisxListem[0,1]

np.int64(20)

In [26]:
benimMatrisxListem[1:,1]

array([50, 80])

In [25]:
benimMatrisxListem[0:,1]

array([20, 50, 80])

In [27]:
benimMatrisxListem[1:,1:]

array([[50, 60],
       [80, 90]])

In [29]:
yeniListe = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25]]
yeniMatris = np.array(yeniListe)
yeniMatris

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
yeniMatris[[0,2,4]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])